#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#
def maxi(arr):
    max=0
    for i in arr:
        if max<=i:
            max=i
    return max

def birthdayCakeCandles(arr):
    cl=0
    m=maxi(arr)
    for i in arr:
        if i==m:
            cl=cl+1
        
    return cl


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    fptr.write(str(result) + '\n')

    fptr.close()
