#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'funnyString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def mod(x):
    if x >= 0:
        return x
    return x * (-1)


def funnyString(s):
    s = s.upper()
    upper_case = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    rs = s[-1::-1]
    for index in range(1, len(s)):
        if mod(upper_case.index(s[index]) - upper_case.index(s[index - 1])) == mod(
            upper_case.index(rs[index]) - upper_case.index(rs[index - 1])
        ):
            pass
        else:
            return "Not Funny"
    return "Funny"

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
