#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'funnyString' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def funnyString(s):
    # Write your code here
    w = ""
    for i in range(len(s)-1,-1,-1):
        w += s[i]
    arr_s = [ord(x) for x in s]
    arr_w = [ord(x) for x in w]
    
    diff_s = [abs(arr_s[i]-arr_s[i+1]) for i in range(0,len(arr_s)-1)]
    diff_w = [abs(arr_w[i]-arr_w[i+1]) for i in range(0,len(arr_w)-1)]
    if diff_s == diff_w:
        return "Funny"
    else:
        return "Not Funny"    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = funnyString(s)

        fptr.write(result + '\n')

    fptr.close()
