import { writeFile } from "node:fs/promises";

const solutions = {
  "https://www.hackerrank.com/rest/contests/master/challenges/solve-me-first/hackers/nmeera2024/download_solution":
    "\n\ndef solveMeFirst(a,b):\n\treturn a+b\n\n\nnum1 = int(input())\nnum2 = int(input())\nres = solveMeFirst(num1,num2)\nprint(res)\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/simple-array-sum/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'simpleArraySum' function below.\n#\n# The function is expected to return an INTEGER.\n# The function accepts INTEGER_ARRAY ar as parameter.\n#\n\ndef simpleArraySum(ar):\n    # Write your code here\n    array_sum = 0\n    for element in ar:\n        array_sum += element\n    return array_sum\n        \n\nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    ar_count = int(input().strip())\n\n    ar = list(map(int, input().rstrip().split()))\n\n    result = simpleArraySum(ar)\n\n    fptr.write(str(result) + '\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/compare-the-triplets/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'compareTriplets' function below.\n#\n# The function is expected to return an INTEGER_ARRAY.\n# The function accepts following parameters:\n#  1. INTEGER_ARRAY a\n#  2. INTEGER_ARRAY b\n#\n\ndef compareTriplets(a, b):\n    i = 0\n    result = [0,0]\n    while(i<3):\n        if(a[i]<b[i]):\n            result[1]+=1\n        elif(a[i]==b[i]):\n            None\n        else:\n            result[0]+=1\n        i = i+1\n    return result\n\nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    a = list(map(int, input().rstrip().split()))\n\n    b = list(map(int, input().rstrip().split()))\n\n    result = compareTriplets(a, b)\n\n    fptr.write(' '.join(map(str, result)))\n    fptr.write('\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/a-very-big-sum/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'aVeryBigSum' function below.\n#\n# The function is expected to return a LONG_INTEGER.\n# The function accepts LONG_INTEGER_ARRAY ar as parameter.\n#\n\ndef aVeryBigSum(ar):\n    sum = 0\n    for elements in ar:\n        sum += elements\n    return sum\n    \n\nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    ar_count = int(input().strip())\n\n    ar = list(map(int, input().rstrip().split()))\n\n    result = aVeryBigSum(ar)\n\n    fptr.write(str(result) + '\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/diagonal-difference/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'diagonalDifference' function below.\n#\n# The function is expected to return an INTEGER.\n# The function accepts 2D_INTEGER_ARRAY arr as parameter.\n#\n\ndef diagonalDifference(arr):\n    # Write your code here\n    i,j = 0,0\n    row_len = len(arr)\n    col_len = len(arr[0]) if row_len> 0 else 0\n    left_diagonal_sum, right_diagonal_sum =0,0\n    for i in range (row_len):\n        for j in range (col_len):\n            if(i==j):\n                left_diagonal_sum+=arr[i][j]\n            if(i+j==row_len-1):\n                right_diagonal_sum+=arr[i][j]\n            j+=1\n        i+=1\n        \n    '''\n    for i in range(row_len):\n        left_diagonal_sum+=arr[i][i]\n        right_diagonal_sum+=arr[i][row_len-1-i]\n        \n    '''\n    \n    return abs(left_diagonal_sum-right_diagonal_sum)\n\nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    n = int(input().strip())\n\n    arr = []\n\n    for _ in range(n):\n        arr.append(list(map(int, input().rstrip().split())))\n\n    result = diagonalDifference(arr)\n\n    fptr.write(str(result) + '\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/plus-minus/hackers/nmeera2024/download_solution":
    '#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the \'plusMinus\' function below.\n#\n# The function accepts INTEGER_ARRAY arr as parameter.\n#\n\ndef plusMinus(arr):\n    # Write your code here\n    negel, zeroel, posel = 0,0,0\n    for element in arr:\n        if element<0:\n            negel+=1\n        elif element==0:\n            zeroel+=1\n        else:\n            posel+=1\n    \n    negel = negel/len(arr)\n    zeroel = zeroel/len(arr)\n    posel = posel/len(arr)\n    \n    print(f"{posel:.6f}")\n    print(f"{negel:.6f}")\n    print(f"{zeroel:.6f}")\n            \n\nif __name__ == \'__main__\':\n    n = int(input().strip())\n\n    arr = list(map(int, input().rstrip().split()))\n\n    plusMinus(arr)\n',
  "https://www.hackerrank.com/rest/contests/master/challenges/staircase/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'staircase' function below.\n#\n# The function accepts INTEGER n as parameter.\n#\n\ndef staircase(n):\n    # Write your code here\n    for i in range(1,n+1):\n        print((n-i)*' '+(i)*'#')\n            \n\nif __name__ == '__main__':\n    n = int(input().strip())\n\n    staircase(n)\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/mini-max-sum/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'miniMaxSum' function below.\n#\n# The function accepts INTEGER_ARRAY arr as parameter.\n#\n\ndef miniMaxSum(arr):\n    # Write your code here\n    minsum, maxsum = 0,0\n    newarr = sorted(arr)\n    minsum = newarr[0]+newarr[1]+newarr[2]+newarr[3]\n    maxsum = newarr[1]+newarr[2]+newarr[3]+newarr[4]\n    \n    print(minsum,maxsum)\n\nif __name__ == '__main__':\n\n    arr = list(map(int, input().rstrip().split()))\n\n    miniMaxSum(arr)\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/birthday-cake-candles/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'birthdayCakeCandles' function below.\n#\n# The function is expected to return an INTEGER.\n# The function accepts INTEGER_ARRAY candles as parameter.\n#\n\ndef birthdayCakeCandles(candles):\n    # Write your code here\n    maximum = max(candles)\n    return candles.count(maximum)\n        \n\nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    candles_count = int(input().strip())\n\n    candles = list(map(int, input().rstrip().split()))\n\n    result = birthdayCakeCandles(candles)\n\n    fptr.write(str(result) + '\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/time-conversion/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'timeConversion' function below.\n#\n# The function is expected to return a STRING.\n# The function accepts STRING s as parameter.\n#\n\ndef timeConversion(time1):\n    # Write your code here\n    length = len(time1)\n    time2 = time1[0:length-2]\n    hourtime = time1[0:2]\n    remainingtime = time2[3:8]\n    time_period = time1[8:9]\n    int_hourtime = int(hourtime)\n\n    if(time_period=='A' and int_hourtime==12):\n        int_hourtime=00\n    elif(time_period=='P' and 1<=int_hourtime<=11):\n        int_hourtime+=12\n    \n    hourtime = str(int_hourtime).zfill(2)\n    return(hourtime+':'+remainingtime)\n\n\nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    s = input()\n\n    result = timeConversion(s)\n\n    fptr.write(result + '\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/grading/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'gradingStudents' function below.\n#\n# The function is expected to return an INTEGER_ARRAY.\n# The function accepts INTEGER_ARRAY grades as parameter.\n#\n\ndef gradingStudents(grades):\n    # Write your code here\n    #length = len(grades)\n    new_grade = []\n    for elem in grades:\n        if(38<=elem<=100):\n            nearest_multiple = ((elem//5)+1)*5\n            if(nearest_multiple-elem<3):\n                new_grade.append(nearest_multiple)\n            else:\n                new_grade.append(elem)\n        else:\n            new_grade.append(elem)\n                \n    return new_grade\n        \n            \nif __name__ == '__main__':\n    fptr = open(os.environ['OUTPUT_PATH'], 'w')\n\n    grades_count = int(input().strip())\n\n    grades = []\n\n    for _ in range(grades_count):\n        grades_item = int(input().strip())\n        grades.append(grades_item)\n\n    result = gradingStudents(grades)\n\n    fptr.write('\\n'.join(map(str, result)))\n    fptr.write('\\n')\n\n    fptr.close()\n",
  "https://www.hackerrank.com/rest/contests/master/challenges/apple-and-orange/hackers/nmeera2024/download_solution":
    "#!/bin/python3\n\nimport math\nimport os\nimport random\nimport re\nimport sys\n\n#\n# Complete the 'countApplesAndOranges' function below.\n#\n# The function accepts following parameters:\n#  1. INTEGER s\n#  2. INTEGER t\n#  3. INTEGER a\n#  4. INTEGER b\n#  5. INTEGER_ARRAY apples\n#  6. INTEGER_ARRAY oranges\n#\n\ndef countApplesAndOranges(s, t, a, b, apples, oranges):\n    # Write your code here\n    apple_fall = []\n    orange_fall = []\n    apple_count, orange_count = 0,0\n\n    #print(apple_fall, orange_fall)\n    for elem in range(0,len(apples)):\n        apple_fall.append(apples[elem]+a)\n    for elem in range(0,len(oranges)):\n        orange_fall.append(oranges[elem]+b)\n        \n    for elem in range(0,len(apple_fall)):\n        if(s<=apple_fall[elem]<=t):\n            apple_count+=1\n    for elem in range(0,len(orange_fall)):\n        if(s<=orange_fall[elem]<=t):\n            orange_count+=1\n            \n    print(apple_count)\n    print(orange_count)\n  \n\nif __name__ == '__main__':\n    first_multiple_input = input().rstrip().split()\n\n    s = int(first_multiple_input[0])\n\n    t = int(first_multiple_input[1])\n\n    second_multiple_input = input().rstrip().split()\n\n    a = int(second_multiple_input[0])\n\n    b = int(second_multiple_input[1])\n\n    third_multiple_input = input().rstrip().split()\n\n    m = int(third_multiple_input[0])\n\n    n = int(third_multiple_input[1])\n\n    apples = list(map(int, input().rstrip().split()))\n\n    oranges = list(map(int, input().rstrip().split()))\n\n    countApplesAndOranges(s, t, a, b, apples, oranges)\n",
};

Object.entries(solutions).forEach(async ([url, solution]) => {
  await writeFile(
    `./${url.split("/")[7]}/${url.split("/")[9]}`,
    solution,
    "utf-8"
  );
});
