#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s):
    zone=s[8:]
    if zone=="PM":
        hour= 12+int(s[0:2])
        if hour>=24:
            hour=hour-12
        return str(hour)+s[2:8]
    elif zone=="AM" and s[0:2]=="12":
        return "00"+s[2:8]
            
    else:
        return s[0:8]

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
