#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'breakingRecords' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY scores as parameter.
#

def breakingRecords(scores):
    # Write your code here
    highest_score = scores[0]
    highest_score_change = 0
    lowest_score = scores[0]
    lowest_score_change = 0
    for i in range(1, len(scores)):
        if scores[i] > highest_score:
            highest_score_change += 1
            highest_score = scores[i]
    for i in range(1, len(scores)):
        if scores[i] < lowest_score:
            lowest_score_change += 1
            lowest_score = scores[i]
    return [highest_score_change, lowest_score_change]        
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
