#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bonAppetit' function below.
#
# The function accepts following parameters:
#  1. INTEGER_ARRAY bill
#  2. INTEGER k
#  3. INTEGER b
#

def bonAppetit(bill, k, b):
    total_bill = 0
    for item in bill:
        total_bill += item
        
    anna_real_amount = int((total_bill - bill[k])/2)
    
    if anna_real_amount == b:
        print("Bon Appetit")
    
    else:
        print(f"{b - anna_real_amount}")    
        
    # Write your code here

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    bill = list(map(int, input().rstrip().split()))

    b = int(input().strip())

    bonAppetit(bill, k, b)
