#!/bin/python3

import sys

def taumBday(b, w, x, y, z):
    # Complete this function
    if(abs(x-y)<=z):
        return b*x + w*y
    if(x<y):
        return b*x + w*(x+z)
    return w*y + b*(y+z)

if __name__ == "__main__":
    t = int(input().strip())
    for a0 in range(t):
        b, w = input().strip().split(' ')
        b, w = [int(b), int(w)]
        x, y, z = input().strip().split(' ')
        x, y, z = [int(x), int(y), int(z)]
        result = taumBday(b, w, x, y, z)
        print(result)
