#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'jumpingOnClouds' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY c as parameter.
#

def jumpingOnClouds(c):
    count=0
    index=0
    try:
        while(index<len(c)-1):
            if c[index+2]==0:
                count=count+1
                index=index+2
            elif c[index+1]==0:
                count=count+1
                index=index+1
        return count 
    except IndexError:
                count=count+1
                return count
  


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
