#!/bin/python3

import sys

def hackerrankInString(s):
    # Complete this function
    cut=0
    for i in 'hackerrank':
        if i in s:
            cut=s.index(i)
            s=s[cut+1:]
        else:
            return 'NO'
    return 'YES'
            

if __name__ == "__main__":
    q = int(input().strip())
    for a0 in range(q):
        s = input().strip()
        result = hackerrankInString(s)
        print(result)
