#!/bin/python3

import math
import os
import random
import re
import sys

# n % d == 0
# Complete the 'findDigits' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def findDigits(n):
    # Write your code here
    divisor_count = 0
    zero_count = 0
    string_n = str(n)
    
    for s in string_n:
        if s == '0':
            zero_count += 1
        else:
            integer_s = int(s)
            if n % integer_s == 0:
                divisor_count += 1
                    
    return divisor_count
     

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        result = findDigits(n)

        fptr.write(str(result) + '\n')

    fptr.close()
