#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'flippingBits' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts LONG_INTEGER n as parameter.
#

def flippingBits(n):
    # Write your code here
    input_in_32bin = format(n,'032b')
    list_input_32bin = list(input_in_32bin)
    transformed_bin = []
    for i in list_input_32bin:
        if i == '0':
            transformed_bin.append(1)
        else:
            transformed_bin.append(0)
    string_transformed_bin = [str(i) for i in transformed_bin]
    s = "".join(string_transformed_bin)
    return (int(s,2))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        n = int(input().strip())

        result = flippingBits(n)

        fptr.write(str(result) + '\n')

    fptr.close()
