#!/bin/python3

import sys

def extraLongFactorials(n):
    # Complete this function
    if n==0:
        return 0
    fact=1
    for i in range(1,n+1):
        fact*=i
    print(fact)

if __name__ == "__main__":
    n = int(input().strip())
    extraLongFactorials(n)
