#!/bin/python3

import sys

def maximizingXor(l, r):
    # Complete this function
    maxNum=0
    for i in range(l,r+1):
        for j in range(i,r+1):
            maxNum=max(maxNum,i^j)
    return maxNum

if __name__ == "__main__":
    l = int(input().strip())
    r = int(input().strip())
    result = maximizingXor(l, r)
    print(result)
