#!/bin/python3

import sys

def lonelyinteger(a):
    # Complete this function
    number=0
    for i in a:
        number^=i
    return number

n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
result = lonelyinteger(a)
print(result)
