#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(steps, path):
    # Write your code here
    d = []
    e = 0
    f = []
    v = 0
    
    for step in path:
        if step == "D":
            d.append(-1)
        else:
            d.append(1)
            
    for i in d:
        e += i
        f.append(e)
    
    for j in range(1, len(f)):
        if f[j] == 0 and f[j-1] == -1:
            v += 1
    return v         
        
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
