#!/bin/python3

import sys

def commonChild(s1, s2):
    # Complete this function
    common = set(s1) & set(s2)
    s1 = ''.join([c for c in s1 if c in common])
    s2 = ''.join([c for c in s2 if c in common])
    previous = [0 for i in range(len(s1) + 1)]
    current = previous
    
    for i in range(1, len(s2) + 1):
        for j in range(1, len(s1) + 1):
            if s2[i - 1] != s1[j - 1]:
                if previous[j] > current[j - 1]:
                    current[j] = previous[j]
                else:
                    current[j] = current[j - 1] 
            else:
                current[j] = previous[j - 1] + 1
        previous = current[::]
    return current[-1]

s1 = input().strip()
s2 = input().strip()
result = commonChild(s1, s2)
print(result)
