#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def caesarCipher(s, k):
    lowerCase = "abcdefghijklmnopqrstuvwxyz"
    upper_case="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    new_string = ""
    for char in s:
        if char.isalpha():
            if char in lowerCase:
                new_string = new_string + lowerCase[(lowerCase.index(char) + k) % len(lowerCase)]
            else:
                new_string = new_string + upper_case[(upper_case.index(char) + k) % len(upper_case)]
                

        else:
            new_string = new_string + char
            
    return new_string

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
