#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'caesarCipher' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER k
#

def caesarCipher(s, k):
    alpbhabets_string = "abcdefghijklmnopqrstuvwxyz"
    alphabets_list = list(alpbhabets_string)

    list_s = list(s)
    for i in range(0,len(list_s)):
        if list_s[i] in alphabets_list:
            list_s[i] = alphabets_list[(alphabets_list.index(list_s[i])+k)%26]
        elif list_s[i].lower() in alphabets_list:
            list_s[i] = (alphabets_list[(alphabets_list.index(list_s[i].lower()) + k)%26]).upper()
    return ("".join(list_s))
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    s = input()

    k = int(input().strip())

    result = caesarCipher(s, k)

    fptr.write(result + '\n')

    fptr.close()
