#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
    range_list=max(arr)+1
    sorted_list=[]
    frequency_list=[]
    for count in range(0,range_list,1):
        frequency_list.append(0)
    for value in arr:
        frequency_list[value]=frequency_list[value]+1
    for index in range(len(frequency_list)):
        j=frequency_list[index]
        while(j>0):
            sorted_list.append(index)
            j=j-1
    return sorted_list        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
