#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
    # Write your code here
    a = [0]*100
    for i in range(0,len(a)):
        a[i] = arr.count(i)
#a contains counts of 0,1,2,..,99        
    b = []
#b is empty array    
    for i in range(0,len(a)):
        if a[i] > 0:
            b += ([i]*a[i])
    return b       
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
