#!/bin/python3

import sys

def staircase(n):
    # Complete this function
    for i in range(n):
        print(' '*(n-i-1)+'#'*(i+1))
if __name__ == "__main__":
    n = int(input().strip())
    staircase(n)
