#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    p=0 #Positive
    n=0 # negative
    z=0 #Zero
    for i in arr:
        if i>0:
            p=p+1
        elif i==0:
            z=z+1
            
        else:
            n=n+1
    pos=p/len(arr)
    neg=n/len(arr)
    zero=z/len(arr)
    print("{:.6f}".format(pos),"{:.6f}".format(neg),"{:.6f}".format(zero),sep="\n")



if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
