#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    num_pos = 0
    num_neg = 0
    num_zero = 0
    n = len(arr)
    
    for i in arr:
        if i > 0:
            num_pos += 1
        elif i < 0:
            num_neg += 1
        else:
            num_zero += 1
            
    ratio_pos = num_pos/n
    ratio_neg = num_neg/n
    ratio_zero = num_zero/n
           
    print(f"{round(ratio_pos,6)}")
    print(f"{round(ratio_neg,6)}")            
    print(f"{round(ratio_zero,6)}")            
           

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
