#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    # Write your code here
    b.sort()
    b_min = b[0]
    d = []    
    for j in range(1, b_min + 1):
        c = 0
        for i in b:
            if i % j == 0:
                c += 1
        if c == len(b):
            d.append(j)
    h = []       
    for k in d:
        e = 0
        for l in a:
            if k % l == 0:
                e += 1
        if e == len(a):
            h.append(k)
    return len(h)         
            
            
                 
            
                  
        
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
