#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    # Write your code here
    minsum, maxsum = 0,0
    newarr = sorted(arr)
    minsum = newarr[0]+newarr[1]+newarr[2]+newarr[3]
    maxsum = newarr[1]+newarr[2]+newarr[3]+newarr[4]
    
    print(minsum,maxsum)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
