#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    # Write your code here
    # #peopl
    i = 5
    # #likes
    l = 0
    # #shared which becomes i
    likes = []
    
    for d in range(1,n+1):
        l = math.floor(i/2)
        likes.append(l)
        s = l*3
        i = s
        
    return sum(likes)    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
 
