#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'bigSorting' function below.
#
# The function is expected to return a STRING_ARRAY.
# The function accepts STRING_ARRAY unsorted as parameter.
#

def Sorting(unsorted):
    l=[]
    for big in unsorted:
        l.append(int(big))
        print(int(big))
    return sorted(l)
def bigSorting(unsorted):
    l=[]
    unsorted=Sorting(unsorted)
    for big in unsorted:
        l.append(str(big))
    return (l) 


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    unsorted = []

    for _ in range(n):
        unsorted_item = input()
        unsorted.append(unsorted_item)

    result = bigSorting(unsorted)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
