#!/bin/python3

import sys

def minimumAbsoluteDifference(n, arr):
    # Complete this function
    arr.sort()
    diff=[]
    for i in range(len(arr)-1):
        diff.append(abs(arr[i]-arr[i+1]))
    return min(diff)

if __name__ == "__main__":
    n = int(input().strip())
    arr = list(map(int, input().strip().split(' ')))
    result = minimumAbsoluteDifference(n, arr)
    print(result)
