#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'marsExploration' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def marsExploration(s):
    count = 0
    bit = "SOS"
    for index in range(0, len(s) - 2, 3):
        rbit=s[index : index + 3]
        #print(s[index : index + 3], index, index + 3)
        if s[index : index + 3] != bit:
            for x,y in zip(bit,rbit):
                if x!=y:
                    count=count+1
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = marsExploration(s)

    fptr.write(str(result) + '\n')

    fptr.close()
