#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'weightedUniformStrings' function below.
#
# The function is expected to return a STRING_ARRAY.
# The function accepts following parameters:
#  1. STRING s
#  2. INTEGER_ARRAY queries
#

def weightedUniformStrings(s, queries):
    # Write your code here
    alphabet_list = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
    
    list_s = list(s)
    set_s = set(s)
    print(set_s)
    counts_s = [(x,list_s.count(x)) for x in set_s]

    uniform_weights = []
    for x in counts_s:
        for i in range(1,x[1]+1):
            uniform_weights.append((alphabet_list.index(x[0])+1)*i)
    output = []
    for j in queries:
        if j in uniform_weights:
            output.append("Yes")
        else:
            output.append("No")    
            
        
    return output

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    queries_count = int(input().strip())

    queries = []

    for _ in range(queries_count):
        queries_item = int(input().strip())
        queries.append(queries_item)

    result = weightedUniformStrings(s, queries)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
