#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    #s->sam house starting point 
    #t-> sam house ending point
    #a-> apple tree origin
    #b-> orrange tree origin 
    #apples reference coordinate of falling apples 
    # oranges-> reference coordinate of falling oranges
    apple_count=0
    orange_count=0
    for apple in apples:
        if apple+a>=s and apple+a<=t:
            apple_count=apple_count+1
    print(apple_count)        
            
    for orange in oranges:
        if orange+b>=s and orange+b<=t:
            orange_count=orange_count+1
    print(orange_count)             

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
