#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Write your code here
    apple_fall = []
    orange_fall = []
    apple_count, orange_count = 0,0

    #print(apple_fall, orange_fall)
    for elem in range(0,len(apples)):
        apple_fall.append(apples[elem]+a)
    for elem in range(0,len(oranges)):
        orange_fall.append(oranges[elem]+b)
        
    for elem in range(0,len(apple_fall)):
        if(s<=apple_fall[elem]<=t):
            apple_count+=1
    for elem in range(0,len(orange_fall)):
        if(s<=orange_fall[elem]<=t):
            orange_count+=1
            
    print(apple_count)
    print(orange_count)
  

if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    s = int(first_multiple_input[0])

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
