#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'makingAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING s1
#  2. STRING s2
#
def list_coverter(s):
    l=[]
    for value in s:
        l.append(value)
    return l

def makingAnagrams(s1, s2):
    count=0
    s1=list_coverter(s1)
    s2=list_coverter(s2)
    for char in s2:
        if char in s1:
            s1.remove(char)
        else:
            count=count+1
            #s2.remove(char)      
            
    return count+len(s1)        
 
   
         
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = makingAnagrams(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
