#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'makingAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING s1
#  2. STRING s2
#

def makingAnagrams(s1, s2):
    # Write your code here
    delete = 0
    for x in set(s2):
        if x not in set(s1):
            delete += s2.count(x)
        elif x in set(s1):
            delete += abs(s1.count(x)-s2.count(x))
    for x in set(s1):
        if x not in set(s2):
            delete += s1.count(x)
    return delete

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s1 = input()

    s2 = input()

    result = makingAnagrams(s1, s2)

    fptr.write(str(result) + '\n')

    fptr.close()
