#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gemstones' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING_ARRAY arr as parameter.
#

def gemstones(arr):
    # Write your code here
    str_arr = "".join(arr)
    set_arr = set(str_arr)
    print(set_arr)
    mineral_count = 0
    for i in set_arr:
        c = 0
        for x in arr:
            if i in x:
                c+=1
        if c == len(arr):
            mineral_count +=1
    return (mineral_count)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr_item = input()
        arr.append(arr_item)

    result = gemstones(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
