#!/bin/python3

import sys

def gemstones(arr):
    # Complete this function
    elem=[set(i) for i in arr]
    prev=elem[0]
    
    for i in elem:
        prev=i.intersection(prev)
    
    return len(prev)


n = int(input().strip())
arr = []
arr_i = 0
for arr_i in range(n):
   arr_t = str(input().strip())
   arr.append(arr_t)
result = gemstones(arr)
print(result)
