#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gameOfThrones' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def gameOfThrones(s):
    # Write your code here
    set_string = set(s)
    counts = [s.count(x) for x in set_string]
    even_odd_counts = [y%2 for y in counts]
    if even_odd_counts.count(1) > 1:
        return "NO"
    else:
        return "YES"    
    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = gameOfThrones(s)

    fptr.write(result + '\n')

    fptr.close()
