#!/bin/python3

import sys
from collections import Counter

def gameOfThrones(s):
    # Complete this function
    odd = 0
    s1 = Counter(s)
    for each in s1.values():
        if each % 2 != 0:
            odd += 1
            if odd > 1:
                return 'NO'
    return ('YES')

s = input().strip()
result = gameOfThrones(s)
print(result)
