#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the 'cavityMap' function below.
# The function is expected to return a STRING_ARRAY.
# The function accepts STRING_ARRAY grid as parameter.

def cavityMap(grid):
    cav_loc = []
    for i in range(1,n-1):
        for j in range(1,n-1):
            if int(grid[i][j]) > int(grid[i][j+1]) and int(grid[i][j]) > int(grid[i][j-1]) and int(grid[i][j]) > int(grid[i+1][j]) and int(grid[i][j]) > int(grid[i-1][j]):
                cav_loc.append((i,j))
    print(cav_loc)
    crib = []
    for x in grid:
        crib.append(list(x))

    for k in cav_loc:
        crib[k[0]][k[1]] = 'X'
    blimp = []
    for l in crib:
        blimp.append(''.join(l))
    return blimp      
                
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    grid = []

    for _ in range(n):
        grid_item = input()
        grid.append(grid_item)

    result = cavityMap(grid)

    fptr.write('\n'.join(result))
    fptr.write('\n')

    fptr.close()
