#!/bin/python3

import os
import sys

#
# Complete the getMoneySpent function below.
#
def des_sort(l):
    l=sorted(l)
    l1=[]
    for i in range(-1,-len(l)-1,-1):
        l1.append(l[i])
    return l1    
        
def getMoneySpent(keyboards, drives, b):
    keyboards=des_sort(keyboards)
    drives=des_sort(drives)
    valid_purchase=[]
    for key in keyboards:
        for d in drives:
            if key+d<=b:
                valid_purchase.append((key+d))
    if len(valid_purchase)==0:
        return -1
    else:
        return max(valid_purchase)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    bnm = input().split()

    b = int(bnm[0])

    n = int(bnm[1])

    m = int(bnm[2])

    keyboards = list(map(int, input().rstrip().split()))

    drives = list(map(int, input().rstrip().split()))

    #
    # The maximum amount of money she can spend on a keyboard and USB drive, or -1 if she can't purchase both items
    #

    moneySpent = getMoneySpent(keyboards, drives, b)

    fptr.write(str(moneySpent) + '\n')

    fptr.close()
