#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'organizingContainers' function below.
#
# The function is expected to return a STRING.
# The function accepts 2D_INTEGER_ARRAY container as parameter.
#
def column_sum(col,matrix):
    col_sum=0
    for row in range(len(matrix)):
        col_sum=col_sum+matrix[row][col]
    return col_sum 

def organizingContainers(container):
    #row_sum=sum(container[0])
    for index in range(len(container)):
        if sum(container[index])== column_sum(index,container):
            return "Possible"
    return "Impossible"    
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        n = int(input().strip())

        container = []

        for _ in range(n):
            container.append(list(map(int, input().rstrip().split())))

        result = organizingContainers(container)

        fptr.write(result + '\n')

    fptr.close()
