#!/bin/python3

import sys

def gameOfStones(n):
    # Complete this function
    return ["First","Second"][n%7 in [0,1]]
    
        
    

if __name__ == "__main__":
    t = int(input().strip())
    for a0 in range(t):
        n = int(input().strip())
        result = gameOfStones(n)
        print(result)
