#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
    # Write your code here
    #length = len(grades)
    new_grade = []
    for elem in grades:
        if(38<=elem<=100):
            nearest_multiple = ((elem//5)+1)*5
            if(nearest_multiple-elem<3):
                new_grade.append(nearest_multiple)
            else:
                new_grade.append(elem)
        else:
            new_grade.append(elem)
    return new_grade

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
