#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'repeatedString' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. STRING s
#  2. LONG_INTEGER n
#

def count_a(s):
    count=0
    for i in s:
        if i=="a":
            count=count+1
    return count        
def repeatedString(s, n):
    add_index=n%len(s)
    round_mul=n//len(s)
    
    count=count_a(s)*round_mul
    
    for i in s[:add_index:1]:
        if i=="a":
            count=count+1
    return count    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
