#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'repeatedString' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. STRING s
#  2. LONG_INTEGER n
#

def repeatedString(s, n):
    # Write your code here
    count_a_in_s = s.count('a')
    length_of_s = len(s)
    if n % length_of_s == 0:
        return (n//length_of_s)*count_a_in_s
    else:
        part_no_of_s = n % length_of_s
        if length_of_s < n:
            return (n//length_of_s)*count_a_in_s + s[0:part_no_of_s].count('a')
        else:
            return s[0:part_no_of_s].count('a')     
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input().strip())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
