#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'palindromeIndex' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def forwordIndexDrop(index,string):
    return string[:index:1]+string[index+1::1]
    
def BackwordIndexDrop(index,string):
    return string[:-len(s)-1+(index+1):-1]+string[index-1::-1]
    
        
def palindromeIndex(s):
    if s==s[::-1]:
        return -1
    elif s[1::]==s[:-len(s):-1]:
        return 0
    for index in range(1,len(s)):
        if BackwordIndexDrop(index,s)==forwordIndexDrop(index,s):
            return index
    return -1    


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = palindromeIndex(s)

        fptr.write(str(result) + '\n')

    fptr.close()
